let obj = {
	id: 36,
	parent_id: 0,
	status: 'processing',
	currency: 'PKR',
	version: '7.7.0',
	prices_include_tax: false,
	date_created: {
		date: '2023-05-25 18:29:35.000000',
		timezone_type: 1,
		timezone: '+00:00',
	},
	date_modified: {
		date: '2023-05-25 18:29:35.000000',
		timezone_type: 1,
		timezone: '+00:00',
	},
	discount_total: '0',
	discount_tax: '0',
	shipping_total: '0',
	shipping_tax: '0',
	cart_tax: '0',
	total: '100',
	total_tax: '0',
	customer_id: 1,
	order_key: 'wc_order_4JL4Ro0ONDhl2',
	billing: {
		first_name: 'Babar',
		last_name: 'Ilyas',
		company: 'khansaab',
		address_1: 'Adil House Mohallah Chishtiabad',
		address_2: 'PO College Doraha',
		city: 'Mansehra',
		state: 'IS',
		postcode: '21300',
		country: 'PK',
		email: 'rahneverd@gmail.com',
		phone: '+923078929420',
	},
	shipping: {
		first_name: 'Babar',
		last_name: 'Ilyas',
		company: 'khansaab',
		address_1: 'Adil House Mohallah Chishtiabad',
		address_2: 'PO College Doraha',
		city: 'Mansehra',
		state: 'IS',
		postcode: '21300',
		country: 'PK',
		phone: '',
	},
	payment_method: 'stripe_cc',
	payment_method_title: 'Visa ending in 4242',
	transaction_id: 'ch_3NBiupIFgUFHTvy503rsZmHQ',
	customer_ip_address: '121.52.146.145',
	customer_user_agent:
		'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
	created_via: 'checkout',
	customer_note: '',
	date_completed: null,
	date_paid: {
		date: '2023-05-25 18:29:36.000000',
		timezone_type: 1,
		timezone: '+00:00',
	},
	cart_hash: 'e1e2f828724f322bd4156a8cc94f9016',
	order_stock_reduced: false,
	download_permissions_granted: false,
	new_order_email_sent: true,
	recorded_sales: false,
	recorded_coupon_usage_counts: false,
	number: '36',
	meta_data: [
		{ id: 1252, key: 'is_vat_exempt', value: 'no' },
		{
			id: 1253,
			key: '_payment_intent_id',
			value: 'pi_3NBiupIFgUFHTvy50k1DtBlT',
		},
		{
			id: 1254,
			key: '_payment_method_token',
			value: 'pm_1NBiuoIFgUFHTvy5Z8qTBasv',
		},
		{ id: 1255, key: '_wc_stripe_mode', value: 'test' },
		{ id: 1257, key: '_wc_stripe_charge_status', value: 'succeeded' },
	],
	line_items: { 43: {} },
	tax_lines: [],
	shipping_lines: { 44: {} },
	fee_lines: [],
	coupon_lines: [],
};
